version: "latest"

services:
  nextjs:
    build: .
    ports:
      - 3000:3000
    environment:
      CUSTOM_ENV: "custom_env"

  nginx:
    depends_on:
      - nextjs
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx:1.23.3
    ports:
      - 8080:80
